### ISSUE TITLE
General Roadmap (Fall 2017)

### ISSUE THREAD

**Issue by ha0ye** [weecology/abundance#3]
## General Considerations
* impending departure by Dave (~ January 2018)

## Data
Look into including new predictor variables:
- [ ] date
- [ ] time
- [ ] land cover
- [ ] spatial scale
- [ ] species life history (bonus, non-trivial to obtain?)

## Modeling

Finish draft model

- [ ] address issues with priors
- [ ] what's going on with the error distribution
- [ ] how to determine degrees of freedom for each species and structure
- [ ] deriving ecological interpretation of last layer

Investigate other models and setups
- [ ] GJAM (see [R package](https://cran.r-project.org/web/packages/gjam/index.html))
- [ ] zoon (see [R package](https://github.com/zoonproject/zoon))
- [ ] establish baselines for prediction (cross-listed to `Automated Evaluation`)

## Automated Evaluation

- [ ] develop proof of concept for Drone on Hipergator
- [ ] implement Drone for CI evaluation
- [ ] define evaluation metrics
- [ ] explore GPU optimization
- [ ] integration of multiple datasets
  plan for:
  * common inputs
    - environmental matrix
    - abundance matrix
  * common outputs
    - log likelihood
    - predictions + uncertainty
    - species specific metrics
- [ ] predictions under future scenarios

**Comment by ha0ye** [comment]
I'll begin by looking into the data (checking in with Shawn), and reading up on zoon.
